### PR TITLE
Provide KeyValuePair methods. Fixes #134

### LINKED ISSUE #134: Provide KeyValuePair.Deconstruct
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2.deconstruct

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by theraot** [comment]
AppVeyor was failing on EditorBrowsableAttribute

Did we not agree that .NET 5.0 is a .NET Core? All LESSTHAN_NETCOREAPP20 targets are LESSTHAN_NET50 targets. Use TARGETS_NET.

There should be no need for "Ex" in KeyValuePairEx.

Performance is going to be bad, with Deconstruct making a copy of the struct.

AggressiveInlining?

I also found that DictonaryEntry got a Deconstruct.

Is this nullable: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair.create?view=net-5.0 I see a ? there. I think that is an error in the documentation.

See also: https://github.com/dotnet/coreclr/blob/81033d3d863004e2535e08b7b78b7dda35228253/src/mscorlib/src/System/Collections/Generic/KeyValuePair.cs

**Comment by NN---** [comment]
> 
> AppVeyor was failing on EditorBrowsableAttribute
Fixed

> 
> Did we not agree that .NET 5.0 is a .NET Core? All LESSTHAN_NETCOREAPP20 targets are LESSTHAN_NET50 targets. Use TARGETS_NET.
Right. My mistake :)

> 
> There should be no need for "Ex" in KeyValuePairEx.
There will be collision with the original class.

> 
> Performance is going to be bad, with Deconstruct making a copy of the struct.
> 
> AggressiveInlining?
> 
Good question, I can add it.
.NET 5.0 doesn't use this attribute.

> I also found that DictonaryEntry got a Deconstruct.
Sure, this can be added.

> 
> Is this nullable: [docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair.create?view=net-5.0](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair.create?view=net-5.0) I see a ? there. I think that is an error in the documentation.
> 
> See also: [dotnet/coreclr@`81033d3`/src/mscorlib/src/System/Collections/Generic/KeyValuePair.cs](https://github.com/dotnet/coreclr/blob/81033d3d863004e2535e08b7b78b7dda35228253/src/mscorlib/src/System/Collections/Generic/KeyValuePair.cs)

It does work with nullable without any issue:

If `TKey` or `TValue` is nullable then it can hold null as expected.

```cs
using System.Collections.Generic;

#nullable enable

class P
{
    static void Main()
    {
        var kv = KeyValuePair.Create((string?) null, 1);

        (string? k, int v) = kv;
    }
}
```

**Comment by theraot** [comment]
I have added AggressiveInlining in other situations. Although, it does not have to be on the same commit.

**Comment by NN---** [comment]
Added the attribute and DictionaryEntry extension.

**Comment by theraot** [comment]
>> There should be no need for "Ex" in KeyValuePairEx.
>There will be collision with the original class.

Will there be? KeyValuePair would not conflict with KeyValuePair<TKey, TValue> because of the generic parameters. And we don't have to add KeyValuePairEx on targets where KeyValuePair exist, only those were it does not.

**Comment by NN---** [comment]
Right :)

**Comment by theraot** [comment]
It says there is a conflict on the tests project. It appears that Microsoft added the KeyValuePair class via nuget in some targets. I can check that later.

**Comment by NN---** [comment]
Fixed.
Waiting for build

**Pull request merged**
