### PR TITLE
Synchronize nullable attributes with .NET

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by theraot** [comment]
I wonder if everything should be LESSTHAN_NET50.

**Comment by NN---** [comment]
Oh, correct.
I’ll fix

**Comment by theraot** [comment]
That would mean that `TARGETS_NET || LESSTHAN_NET50 || LESSTHAN_NETSTANDARD22` is just `LESSTHAN_NET50`.

**Comment by NN---** [comment]
Actually, NET50 is .NET Core successor  and cannot replace TARGETS_NET.
So everything is correct.

**Comment by theraot** [comment]
Alright.

**Pull request merged**
