### PR TITLE
Produce same hash for ValueTuple with same values

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by theraot** [comment]
Thanks, I will merge this soon, I am in the middle of a big code review.

By the way, I intent to move tests to TestRunner, that test will not run on .NET Standard as is.

**Comment by NN---** [comment]
If you could publish v2 update to nuget, that would be great.
Otherwise I have to wait for v3 release in order to use the library.

Why NUnit is not good enough ?

**Comment by theraot** [comment]
I am stuck in an old version of NUnit because they added backports of their own that conflict with libraries.

Assuming I get a modern NUnit to run... they have dropped support for old .NET Framework targets.

Futhermore, there is extra work to test on .NET Standard regardless of test system because .NET Standard 1.4 and below lack relevant reflection features that prevent discovering tests.

I face similar problems with any of the test systems that AppVeyor supports... meaning I will have to develop a custom test script to run tests with them anyway. That is how I landed in developing my own test system.

**Comment by NN---** [comment]
Use extern alias approach.
You can what I did in CodeJam
https://github.com/rsdn/CodeJam/commit/a6ea729935eddb36b621b81f396b91b74749f461

NUnit 3.11 supports .NET 2.0 so you don't have to worry so much.

**Comment by NN---** [comment]
If you need any help with v3 release, I will gladly help.
I cannot use your library without fixes of ValueTuple.

**Pull request merged**
