### PR TITLE
Add Span and Memory classes.

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by theraot** [comment]
This looks good. And once more thank you taking the time.

It needs tests for slice. Could be based on the examples here: https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-5.0#spant-and-arrays

Do we need to define `TARGET_64BIT`?

I have used `IntPtr.Size == 8` elsewhere.

**Comment by NN---** [comment]
Don’t know about target 64, I just copied the code.
It can be == 8.

**Comment by NN---** [comment]
Didn’t have time for tests:)
There are a lot of things to tests there.

**Comment by NN---** [comment]
What do you think about unsafe code?
Let’s allow it in the library.
There is no additional safety of doing Marshal.ReadInt32 over int* p.
More than that, pointers are type safer :)

**Comment by NN---** [comment]
@theraot So what is the decision about unsafe ?

**Comment by theraot** [comment]
@NN--- I found it: https://github.com/theraot/Theraot/pull/2 @qwertie 

> I needed Theraot.Core to have a "strong name" because any DLL or EXE that has a strong name must only reference assemblies that have a strong name.

**Comment by NN---** [comment]
I guess it is better to create a separate NuGet with unsafe then.

**Comment by NN---** [comment]
I am not sure that strong name requires safe assembly.
mscorlib is not a safe and yet has strong name.
The FullTrust argument is totally correct, luckily it is not relevant in .NET Core does in older .NET Frameworks :(
It seems that the only good solution is to have a separate package for Span/Memory.
The drawback of this solution is that you cannot have Span/Memory overloads in the Theraot library interfaces and solve it only via extensions methods.

**Comment by NN---** [comment]
@theraot What is your suggestion here ?
I think the only solution is a separate NuGet or 2 NuGets for Theraot which is even less convenient.

**Comment by theraot** [comment]
Do you know if Nuget allows to push version numbers older than the latest?

This is what I'm thinking: The demand for Span and Memory goes up, and the demand for not unsafe build goes down. So, we increment version number, and turn on unsafe (and we don't put conditional compilation or anything like that)… 

Now, for people on an environment where they need safe builds only, they would have to stay on the old version. So that works. If somebody still need them, I would like to still be able to bugfix those. Then the bugfixes could be version numbers between the current one and whatever version number we give the first unsafe build.

Now, everything else being equal, if we need to release a safe build, we branch, insert conditional compilation to remove whatever has unsafe code, and publish that.

**Comment by theraot** [comment]
I think I'll finish one more release before that. I haven't release a version fixing the ConcurrentDictionary issue. And doing this with that bug open will, well, bug me.

**Comment by NN---** [comment]
What is the plan?
Move to unsafe and require FullTrust ?
Another option to create 2 different libraries , however I don’t think FullTrust is a problem.

**Pull request merged**
