### PR TITLE
Add .NET 5.0 compiler classes and attributes. Fixes #135

### LINKED ISSUE #135: Provide IsExternalInit
Type: System.Runtime.CompilerServices.IsExternalInit

Reference: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.isexternalinit?view=net-5.0

See also: https://blog.ndepend.com/using-c9-record-and-init-property-in-your-net-framework-4-x-net-standard-and-net-core-projects/

### PR DESCRIPTION
**Pull request by NN---**

### CODE REVIEW

**Comment by theraot** [comment]
What is SYSTEM_PRIVATE_CORELIB?

We should add IsExternalInit to the nuget description.

And thank you for taking the time to add these.

**Comment by NN---** [comment]
> 
> 
> What is SYSTEM_PRIVATE_CORELIB?
> 

The code is copied from .NET sources.
I can remove it.

> We should add IsExternalInit to the nuget description.

What is nuget description ?

> 
> And thank you for taking the time to add these.

🍻

**Comment by theraot** [comment]
Well, I meant tags...

See https://github.com/theraot/Theraot/blob/master/Framework.Core/Framework.Core.csproj

There is PackageTags, those go in the nuget. But well, yeah, Description too.

I also need to remember to increment the version(s), before making the nuget.

**Comment by theraot** [comment]
> I can remove it.

Yes, remove SYSTEM_PRIVATE_CORELIB

**Pull request merged**
